import asyncio
import random
import logging
from playwright.async_api import Page
log = logging.getLogger(__name__)

# ==========================================
# 📧 MASSIVE NEWSLETTER URLS LIST
# All Substack, Beehiiv, Ghost, ConvertKit, and standardized
# newsletter platforms — highly uniform HTML = flawless automation.
# ==========================================
NEWSLETTER_URLS = [

    # ---- Tech & Software Engineering ----
    "https://thepragmaticengineer.substack.com/",
    "https://lennyrachitsky.substack.com/",
    "https://tldr.tech/",
    "https://platformer.news/",
    "https://www.densediscovery.com/",
    "https://softwareleadweekly.com/",
    "https://devopsweekly.com/",
    "https://frontendfoc.us/",
    "https://javascriptweekly.com/",
    "https://nodeweekly.com/",
    "https://reactnewsletter.com/",
    "https://pythonweekly.com/",
    "https://rubyweekly.com/",
    "https://golangweekly.com/",
    "https://rustacean-station.org/",
    "https://dbweekly.com/",
    "https://postgresweekly.com/",
    "https://mobiledevweekly.com/",
    "https://androidweekly.net/",
    "https://iosdevweekly.com/",
    "https://swiftweeklybrief.com/",
    "https://kotlinweekly.net/",
    "https://codewithjason.com/rails-with-jason-newsletter/",
    "https://laravelweekly.com/",
    "https://www.pointer.io/",
    "https://cassidoo.co/newsletter/",
    "https://www.techpays.email/",
    "https://www.programmingdigest.net/",
    "https://levelupcodingweekly.com/",
    "https://weeklydevelopernewsletter.com/",
    "https://statuscode.substack.com/",
    "https://changelog.com/weekly",
    "https://css-weekly.com/",
    "https://webdesignweekly.com/",
    "https://smashingmagazine.com/the-smashing-newsletter/",
    "https://www.codrops.com/newsletter/",
    "https://sidebar.io/",
    "https://designcode.io/newsletter",
    "https://syntaxfm.substack.com/",
    "https://www.joshwcomeau.com/email/",
    "https://bytes.dev/",
    "https://thisweekinreact.com/",
    "https://vuejsnews.com/",
    "https://svelteradio.com/",
    "https://deno.news/",
    "https://bun.news/",
    "https://www.serverlessstatusweekly.com/",
    "https://cloudweekly.news/",
    "https://awsweekly.io/",
    "https://lastweekinaws.com/newsletter/",
    "https://www.cloudnative.news/",
    "https://kubeweekly.io/",
    "https://dockerweekly.com/",
    "https://www.cncf.io/newsletter/",

    # ---- AI & Machine Learning ----
    "https://www.therundown.ai/",
    "https://www.aiweekly.co/",
    "https://import-ai.substack.com/",
    "https://thesequence.substack.com/",
    "https://www.deeplearning.ai/the-batch/",
    "https://lastweekinai.substack.com/",
    "https://gradientflow.com/newsletter/",
    "https://www.benedictevans.com/newsletter",
    "https://www.exponentialview.co/",
    "https://www.aitidbits.ai/",
    "https://www.superhuman.ai/",
    "https://aipulse.beehiiv.com/",
    "https://www.aibreakfast.beehiiv.com/",
    "https://www.prompts.co/newsletter",
    "https://www.futuretools.io/newsletter",
    "https://botnirvana.substack.com/",
    "https://theainavigator.substack.com/",
    "https://mlops.community/newsletter/",
    "https://magazine.sebastianraschka.com/",
    "https://www.deeplearning.ai/newsletter/",
    "https://clouded.substack.com/",
    "https://www.aisupremacy.substack.com/",
    "https://www.ailawinsider.substack.com/",
    "https://www.thealgorithmicbridge.substack.com/",
    "https://www.cognitiverevolution.ai/",
    "https://www.lennysnewsletter.com/",

    # ---- Startup & Entrepreneurship ----
    "https://strictlyvc.substack.com/",
    "https://theankler.com/",
    "https://newsletter.thehustle.co/",
    "https://www.morningbrew.com/daily",
    "https://1440.com/",
    "https://www.theskimm.com/",
    "https://www.startuparchive.org/",
    "https://www.seedtable.com/newsletter",
    "https://www.sifted.eu/newsletter",
    "https://thegeneralist.substack.com/",
    "https://www.notboring.co/",
    "https://www.joincolossus.com/newsletter",
    "https://www.crunchbasenews.com/newsletter",
    "https://failory.com/newsletter",
    "https://www.starterstory.com/newsletter",
    "https://www.indiehackers.com/newsletter",
    "https://makermag.com/newsletter/",
    "https://www.productlessons.xyz/",
    "https://www.invisionapp.com/inside-design/newsletter/",
    "https://www.ycombinator.com/newsletter",
    "https://www.firstround.com/newsletter",
    "https://www.sequoiacap.com/newsletter",
    "https://a16z.com/newsletter/",
    "https://www.nfx.com/newsletter",
    "https://www.saastr.com/newsletter/",
    "https://baremetrics.com/blog",
    "https://www.chartmogul.com/newsletter/",
    "https://www.profitwell.com/recur/",
    "https://www.churnbuster.io/newsletter",
    "https://www.latecheckout.substack.com/",
    "https://growthhackers.com/newsletter",
    "https://www.growthmentor.io/newsletter/",
    "https://www.marketingexamples.com/",
    "https://www.swipefiles.com/",
    "https://www.growthinreverse.com/",

    # ---- Business & Finance ----
    "https://numlock.substack.com/",
    "https://www.readmargins.com/",
    "https://www.axios.com/newsletters",
    "https://www.morningstar.com/newsletter",
    "https://www.marketcurrents.beehiiv.com/",
    "https://www.finimize.com/",
    "https://www.milkroad.com/",
    "https://www.stockanalysis.com/newsletter/",
    "https://www.investmentnews.com/newsletter",
    "https://www.bloomberg.com/account/newsletters",
    "https://www.wsj.com/newsletters",
    "https://www.ft.com/newsletters",
    "https://www.economist.com/newsletters",
    "https://www.hbr.org/email-newsletters",
    "https://www.fortune.com/newsletter",
    "https://www.businessinsider.com/newsletters",
    "https://www.cnbc.com/newsletters/",
    "https://www.marketwatch.com/newsletters",
    "https://www.barrons.com/newsletters",
    "https://www.nerdwallet.com/newsletter",
    "https://www.wisebread.com/newsletter",
    "https://affordanything.substack.com/",
    "https://ofdollarsanddata.com/newsletter/",
    "https://awealthofcommonsense.com/newsletter/",
    "https://www.humbledollar.com/",
    "https://www.abnormalreturns.com/",
    "https://www.ditchingdimes.substack.com/",
    "https://www.bankeronwheels.com/newsletter/",
    "https://www.moneyzen.com/newsletter/",
    "https://www.getrichslowly.org/newsletter/",
    "https://www.thefinancebuff.com/newsletter",
    "https://earlyretirementnow.com/newsletter/",
    "https://www.physicianonfire.com/newsletter/",
    "https://www.whitecoatinvestor.com/newsletter/",

    # ---- Crypto & Web3 ----
    "https://www.milkroad.com/",
    "https://www.thecryptobasic.com/newsletter/",
    "https://banklesshq.com/",
    "https://www.coindesk.com/newsletters/",
    "https://www.thedefiant.io/newsletter",
    "https://decrypt.co/newsletter",
    "https://cointelegraph.com/newsletter",
    "https://www.cryptobriefing.com/newsletter/",
    "https://www.messari.io/newsletter",
    "https://www.glassnode.com/newsletter",
    "https://dirtroads.substack.com/",
    "https://www.weeklyblockchain.com/",
    "https://weekinnfts.substack.com/",
    "https://www.nftinsider.xyz/newsletter/",
    "https://proofofwork.news/",
    "https://newsletter.banklesshq.com/",
    "https://thebitcoinlayer.substack.com/",
    "https://www.satswire.co/",
    "https://shrimpyapp.substack.com/",
    "https://www.pomp.letter/",
    "https://www.unchainedcrypto.com/newsletter",
    "https://newsletter.web3weekly.io/",

    # ---- Marketing & Growth ----
    "https://www.marketingweek.com/newsletters/",
    "https://www.convinceandconvert.com/newsletter/",
    "https://www.socialmediaexaminer.com/newsletter/",
    "https://www.nngroup.com/articles/subscribe/",
    "https://www.searchenginejournal.com/newsletter/",
    "https://www.searchengineland.com/newsletter",
    "https://moz.com/blog/subscribe",
    "https://www.semrush.com/blog/newsletter/",
    "https://backlinko.com/newsletter",
    "https://www.ahrefs.com/newsletter",
    "https://neilpatel.com/newsletter/",
    "https://cxl.com/newsletter/",
    "https://www.hubspot.com/marketing-statistics",
    "https://www.contentmarketinginstitute.com/newsletter/",
    "https://www.copyblogger.com/newsletter/",
    "https://www.copyhackers.com/newsletter/",
    "https://kopywritingkourse.com/newsletter/",
    "https://www.emailmastery.com/",
    "https://really good emails.com/newsletter",
    "https://www.emailvendorselection.com/newsletter/",
    "https://emailweekly.co/",
    "https://www.inboxcollective.com/",
    "https://www.emailoctopus.com/blog/newsletter/",
    "https://www.klaviyo.com/blog/newsletter",
    "https://www.mailchimp.com/resources/",
    "https://www.campaignmonitor.com/resources/",
    "https://growthhackers.com/newsletter",
    "https://www.liftletters.com/",
    "https://marketingexamples.substack.com/",
    "https://swipefiles.substack.com/",
    "https://www.thedrum.com/newsletters",
    "https://www.adweek.com/newsletters/",
    "https://www.campaignlive.com/newsletter/",
    "https://www.digiday.com/newsletter/",
    "https://www.marketingdive.com/newsletters/",

    # ---- Design & UX ----
    "https://uxdesignweekly.com/",
    "https://www.nngroup.com/articles/subscribe/",
    "https://www.uxcollective.beehiiv.com/",
    "https://sidebar.io/",
    "https://www.webdesignnews.com/newsletter/",
    "https://www.creativebloq.com/newsletter/",
    "https://www.smashingmagazine.com/the-smashing-newsletter/",
    "https://www.muzli.design/",
    "https://www.designweekly.com/",
    "https://www.typewolf.com/newsletter",
    "https://fontsinuse.com/newsletter",
    "https://www.siteinspire.com/newsletter",
    "https://land-book.com/newsletter",
    "https://www.lapa.ninja/newsletter/",
    "https://www.designspiration.com/newsletter/",
    "https://briefs.video/",
    "https://thedesignteam.io/",
    "https://subtract.substack.com/",
    "https://cofolios.substack.com/",
    "https://www.figma.com/blog/newsletter/",
    "https://www.sketch.com/blog/",

    # ---- Product Management ----
    "https://www.productboard.com/blog/newsletter/",
    "https://www.mindtheproduct.com/newsletter/",
    "https://www.productcoalition.com/newsletter/",
    "https://lethain.com/newsletter/",
    "https://www.reforge.com/newsletter",
    "https://www.producttalk.org/newsletter/",
    "https://www.svpg.com/articles/",
    "https://www.romanpichler.com/newsletter/",
    "https://cutlefish.substack.com/",
    "https://www.gibsonbiddle.com/newsletter",
    "https://productcrunch.substack.com/",
    "https://www.productlessons.xyz/newsletter",
    "https://shreyas.substack.com/",
    "https://www.theverge.com/newsletters",

    # ---- Data Science & Analytics ----
    "https://www.datascienceweekly.org/",
    "https://dataelixir.com/",
    "https://www.oreilly.com/data/newsletter.html",
    "https://www.kdnuggets.com/news/subscribe.html",
    "https://towardsdatascience.com/newsletter",
    "https://www.dataquest.io/blog/newsletter/",
    "https://analyticsvidhya.com/newsletter/",
    "https://datasciencedojo.com/newsletter/",
    "https://www.superdatascience.com/newsletter/",
    "https://www.datanews.io/",
    "https://www.dataeng.club/",
    "https://aiweekly.co/",
    "https://www.datadriven.substack.com/",
    "https://roundup.getdbt.com/",
    "https://www.analytics-weekly.com/",
    "https://www.dataengineeringweekly.com/",
    "https://www.moderndatastack.xyz/newsletter",
    "https://www.datafold.com/blog/newsletter/",
    "https://metriql.com/newsletter/",
    "https://www.elt.news/",

    # ---- Cybersecurity ----
    "https://www.tldrsec.com/",
    "https://www.securethisweek.com/",
    "https://www.securityweekly.com/newsletter/",
    "https://www.darkreading.com/newsletter",
    "https://www.bleepingcomputer.com/news/security/",
    "https://krebsonsecurity.com/",
    "https://www.sans.org/newsletters/",
    "https://www.cisa.gov/subscribe-updates-cisa",
    "https://www.threatpost.com/newsletter/",
    "https://www.infosecurity-magazine.com/newsletter/",
    "https://www.schneier.com/blog/",
    "https://www.hacker newsletter.com/",
    "https://risky.biz/",
    "https://www.scmagazine.com/newsletter",
    "https://www.cyberscoop.com/newsletter/",
    "https://grahamcluley.com/newsletter/",
    "https://www.welivesecurity.com/newsletter/",
    "https://www.malwarebytes.com/newsletter/",
    "https://www.securityweek.com/newsletter",
    "https://www.csoonline.com/newsletter/",

    # ---- Science & Research ----
    "https://www.sciencenews.org/newsletter/",
    "https://www.science.org/action/showLogin",
    "https://www.nature.com/nature/briefing/signup/",
    "https://www.newscientist.com/sign-up/",
    "https://www.scientificamerican.com/newsletter/",
    "https://www.quantamagazine.org/newsletter/",
    "https://www.sciencedaily.com/newsletter.htm",
    "https://www.livescience.com/newsletter",
    "https://www.earth sky.org/newsletter/",
    "https://www.realclearscience.com/newsletter/",
    "https://www.theatlantic.com/science/newsletter/",
    "https://www.wired.com/newsletter/",
    "https://undark.org/newsletter/",
    "https://nautil.us/newsletter/",
    "https://www.discovermagazine.com/newsletter",
    "https://www.popsci.com/newsletters/",
    "https://www.smithsonianmag.com/newsletters/",
    "https://www.cosmosmagazine.com/newsletter/",
    "https://www.chemistryworld.com/newsletter/",
    "https://www.aps.org/publications/newsletters.cfm",

    # ---- Space & Astronomy ----
    "https://www.space.com/newsletter",
    "https://spacenews.com/newsletter/",
    "https://www.universetoday.com/newsletter/",
    "https://www.planetary.org/newsletter",
    "https://skyandtelescope.org/newsletter/",
    "https://www.astronomy.com/newsletter/",
    "https://nasa.gov/subscribe/",
    "https://spacepolicyinstitute.org/newsletter/",
    "https://www.spaceintelreport.com/newsletter/",
    "https://aerosreviews.substack.com/",
    "https://www.spacenews.substack.com/",
    "https://kellybriefing.substack.com/",
    "https://www.thespacereview.com/",
    "https://www.thelaunchpadnewsletter.com/",

    # ---- Health & Medicine ----
    "https://www.webmd.com/email-newsletter/",
    "https://www.healthline.com/newsletter",
    "https://www.mayoclinic.org/newsletters",
    "https://www.health.harvard.edu/newsletter",
    "https://www.clevelandclinic.org/health/newsletter/",
    "https://www.nih.gov/news-events/nih-newsletter",
    "https://www.medpagetoday.com/registrationV2/",
    "https://www.medscape.com/email-newsletters",
    "https://www.healio.com/newsletters",
    "https://www.statNews.com/newsletters/",
    "https://www.moderatorsolutions.com/newsletter/",
    "https://evidence.nih.gov/newsletter",
    "https://www.pharmaceutical-technology.com/newsletter/",
    "https://www.fiercehealthcare.com/newsletters",
    "https://www.modernhealthcare.com/section/newsletters",
    "https://www.beckershospitalreview.com/newsletter.html",
    "https://rockhealth.com/newsletter/",
    "https://www.healthcareitnews.com/newsletter",
    "https://www.mobihealthnews.com/newsletter",
    "https://www.digitalhealth.net/newsletter/",

    # ---- Mental Health & Wellness ----
    "https://www.tenpercent.com/newsletter",
    "https://www.headspace.com/newsletter",
    "https://www.calm.com/blog/newsletter/",
    "https://www.mindful.org/newsletter/",
    "https://www.psychologytoday.com/us/newsletter",
    "https://www.verywellmind.com/newsletter",
    "https://greatergood.berkeley.edu/newsletters",
    "https://www.happify.com/newsletter/",
    "https://www.therapistaid.com/newsletter/",
    "https://www.positivepsychology.com/newsletter/",
    "https://www.nami.org/Support-Education/",
    "https://www.mentalhealthamerica.net/newsletter/",
    "https://wellnesslettersubstack.com/",
    "https://jamesclear.com/3-2-1",
    "https://www.markmanson.net/newsletter",
    "https://www.tim.blog/newsletter",
    "https://www.brainpickings.org/newsletter/",
    "https://cupofjo.com/newsletter/",

    # ---- Fitness & Nutrition ----
    "https://www.menshealth.com/newsletter/",
    "https://www.womenshealthmag.com/newsletter/",
    "https://www.shape.com/newsletter/",
    "https://www.runnersworld.com/newsletter/",
    "https://www.bicycling.com/newsletter/",
    "https://www.triathlete.com/newsletter/",
    "https://www.outsideonline.com/newsletter/",
    "https://www.eatthis.com/newsletter/",
    "https://www.nutritionaction.com/newsletter/",
    "https://examine.com/newsletter/",
    "https://www.precisionnutrition.com/newsletter",
    "https://www.eatright.org/newsletter",
    "https://www.todaysdietitian.com/newsletter/",
    "https://www.bodybuilding.com/newsletter/",
    "https://www.muscleandfitness.com/newsletter/",
    "https://www.nerdfitness.com/newsletter/",
    "https://www.stronglifts.com/newsletter/",
    "https://www.t-nation.com/newsletter/",
    "https://thebiolayne.substack.com/",
    "https://nutrisense.substack.com/",

    # ---- Food & Cooking ----
    "https://www.allrecipes.com/newsletter/",
    "https://www.foodnetwork.com/newsletters",
    "https://www.epicurious.com/newsletter",
    "https://www.seriouseats.com/newsletter/",
    "https://www.bonappetit.com/newsletter/",
    "https://www.saveur.com/newsletter/",
    "https://www.eater.com/newsletters",
    "https://www.food52.com/newsletter/",
    "https://www.thekitchn.com/newsletter/",
    "https://www.kingarthurbaking.com/newsletter/",
    "https://cooking.nytimes.com/newsletters",
    "https://smittenkitchen.com/newsletter/",
    "https://www.davidlebovitz.com/newsletter/",
    "https://www.101cookbooks.com/newsletter/",
    "https://pinchofyum.com/newsletter",
    "https://minimalistbaker.com/newsletter/",
    "https://www.halfbakedharvest.com/newsletter/",
    "https://www.skinnytaste.com/newsletter/",
    "https://www.budgetbytes.com/newsletter/",
    "https://www.wellplated.com/newsletter/",
    "https://www.downshiftology.com/newsletter/",
    "https://www.cookieandkate.com/newsletter/",
    "https://www.gimmesomeoven.com/newsletter/",
    "https://themodernproper.com/newsletter/",
    "https://www.saltandlavender.com/newsletter/",
    "https://www.feastingathome.com/newsletter/",

    # ---- Travel ----
    "https://www.lonelyplanet.com/newsletter/",
    "https://www.travelandleisure.com/newsletter/",
    "https://www.cntraveler.com/newsletter/",
    "https://www.nationalgeographic.com/travel/newsletter/",
    "https://www.roughguides.com/newsletter/",
    "https://www.fodors.com/newsletter/",
    "https://www.thepointsguy.com/newsletter/",
    "https://onemileatatime.com/newsletter/",
    "https://viewfromthewing.substack.com/",
    "https://headforpoints.com/newsletter/",
    "https://millionmilesecrets.com/newsletter/",
    "https://www.travelhacking.org/newsletter/",
    "https://nomadlist.com/newsletter",
    "https://www.remotelyonesubstack.com/",
    "https://www.workingwanderer.com/newsletter/",
    "https://www.theworldpursuit.com/newsletter/",
    "https://expertvagabond.com/newsletter/",
    "https://www.legalnomads.com/newsletter/",
    "https://atlas-diaries.substack.com/",
    "https://www.travel-hack.com/newsletter/",
    "https://www.twowanderingsoles.com/newsletter/",
    "https://www.nomadicmatt.com/newsletter/",
    "https://www.adventurouskate.com/newsletter/",
    "https://www.theblondeabroad.com/newsletter/",
    "https://www.mapmetravel.substack.com/",

    # ---- Politics & World Affairs ----
    "https://www.readtangle.com/",
    "https://numlock.substack.com/",
    "https://www.politico.com/newsletter",
    "https://www.thehill.com/newsletter",
    "https://www.axios.com/newsletters/",
    "https://www.vox.com/newsletter",
    "https://www.theatlantic.com/newsletters/",
    "https://www.newyorker.com/newsletters",
    "https://www.nytimes.com/newsletters/",
    "https://www.washingtonpost.com/newsletters/",
    "https://www.foreignaffairs.com/newsletter",
    "https://foreignpolicy.com/newsletter/",
    "https://www.economist.com/newsletters",
    "https://www.theintercept.com/newsletter/",
    "https://www.propublica.org/newsletters",
    "https://www.thebulwark.com/newsletter/",
    "https://www.theweek.com/newsletter/",
    "https://www.theguardian.com/email-newsletters",
    "https://www.bbc.com/newsletters",
    "https://www.aljazeera.com/newsletter/",
    "https://newsletters.theatlantic.com/",
    "https://heatharmstrong.substack.com/",
    "https://hotair.substack.com/",
    "https://www.commonsense.news/",
    "https://www.racket.news/",
    "https://garbage.substack.com/",

    # ---- Environment & Climate ----
    "https://www.carbonbrief.org/newsletter/",
    "https://www.climatecentral.org/newsletter/",
    "https://grist.org/newsletter/",
    "https://insideclimatenews.org/newsletter/",
    "https://www.eenews.net/newsletter/",
    "https://www.earthday.org/newsletter/",
    "https://www.sierraclub.org/newsletter",
    "https://www.nrdc.org/newsletter",
    "https://www.greenpeace.org/international/newsletter/",
    "https://e360.yale.edu/newsletter/",
    "https://www.climatedocket.com/newsletter/",
    "https://heatmap.news/newsletter",
    "https://www.canarymedia.com/newsletter/",
    "https://www.energymonitor.ai/newsletter/",
    "https://www.rechargenews.com/newsletter/",
    "https://subscriber.cleanenergywire.org/",
    "https://www.pv-magazine.com/newsletter/",
    "https://windpowermonthly.com/newsletter/",
    "https://www.greenbiz.com/newsletter",
    "https://www.sustainablebrands.com/newsletter",
    "https://www.triplepundit.com/newsletter/",
    "https://www.environmentalhealthnews.org/newsletter/",

    # ---- Real Estate & Housing ----
    "https://www.inman.com/newsletters/",
    "https://www.housingwire.com/newsletter/",
    "https://www.therealdeal.com/newsletter/",
    "https://www.bisnow.com/newsletter",
    "https://www.globest.com/newsletter/",
    "https://www.millionacres.com/newsletter/",
    "https://www.curbed.com/newsletter/",
    "https://www.propmodo.com/newsletter/",
    "https://www.realtrends.com/newsletter/",
    "https://www.mortgagenewsdaily.com/newsletters/",
    "https://www.calculatedriskblog.com/",
    "https://www.cooperatornews.com/newsletter/",
    "https://affordanything.substack.com/",
    "https://bigerpockets.substack.com/",
    "https://www.rentalhousingjournal.com/newsletter/",

    # ---- Books & Literature ----
    "https://www.goodreads.com/newsletter",
    "https://www.litreactor.com/newsletter/",
    "https://lithub.com/newsletter/",
    "https://electricliterature.com/newsletter/",
    "https://www.theparisreview.org/newsletter/",
    "https://www.newcriterion.com/newsletter/",
    "https://www.nytimes.com/newsletters/books",
    "https://www.theguardian.com/email-newsletters#books",
    "https://www.newyorker.com/newsletters/books",
    "https://bookriot.com/newsletter/",
    "https://www.epicreads.com/newsletter/",
    "https://www.tor.com/newsletter/",
    "https://www.fantasticfiction.com/newsletter/",
    "https://crimereads.com/newsletter/",
    "https://www.mysterypeople.com/newsletter/",
    "https://thebelladonnascomedy.substack.com/",
    "https://www.nonfictionwriters.com/newsletter/",
    "https://www.shortlisted.co/",
    "https://fivebooks.com/newsletter/",
    "https://kottke.org/newsletter",

    # ---- Parenting & Family ----
    "https://www.parents.com/newsletter/",
    "https://www.babycenter.com/newsletter",
    "https://www.whattoexpect.com/newsletter/",
    "https://www.thebump.com/newsletter/",
    "https://www.todaysparent.com/newsletter/",
    "https://www.fatherly.com/newsletter/",
    "https://www.romper.com/newsletter/",
    "https://www.scarymommy.com/newsletter/",
    "https://www.babble.com/newsletter/",
    "https://www.mommyish.com/newsletter/",
    "https://www.pregnancymagazine.com/newsletter/",
    "https://kellymom.com/newsletter/",
    "https://www.kellymom.com/newsletter/",
    "https://www.zerotothree.org/newsletter/",
    "https://janethesavage.substack.com/",
    "https://www.biglittlefeelings.substack.com/",
    "https://parentingaftertrauma.substack.com/",
    "https://www.tinybeans.com/newsletter/",

    # ---- Education & Learning ----
    "https://www.edutopia.org/newsletter/",
    "https://www.teacherthought.com/newsletter/",
    "https://www.eschoolnews.com/newsletter/",
    "https://www.educationweek.org/section/newsletters",
    "https://edsurge.com/newsletter/",
    "https://www.insidehighered.com/newsletters",
    "https://www.chronicle.com/newsletters",
    "https://www.campustechnology.com/newsletters.aspx",
    "https://www.iste.org/newsletter",
    "https://www.kqed.org/mindshift/newsletter/",
    "https://www.learningforward.org/newsletter/",
    "https://www.ascd.org/el/subscribe",
    "https://districtadministration.com/newsletter/",
    "https://www.nwea.org/newsletter/",
    "https://www.commonsense.org/education/newsletter/",
    "https://classhook.com/newsletter/",
    "https://www.cultofpedagogy.com/newsletter/",
    "https://www.middleweb.com/newsletter/",
    "https://thecornerstoneforteachers.com/newsletter/",

    # ---- Fashion & Style ----
    "https://www.vogue.com/newsletter",
    "https://www.harpersbazaar.com/newsletter/",
    "https://www.elle.com/newsletter/",
    "https://www.glamour.com/newsletter/",
    "https://www.wwd.com/newsletter/",
    "https://www.businessoffashion.com/newsletter/",
    "https://www.fashionista.com/newsletter/",
    "https://www.refinery29.com/en-us/newsletter/",
    "https://www.whowhatwear.com/newsletter/",
    "https://www.thecut.com/newsletter/",
    "https://www.instyle.com/newsletter/",
    "https://www.cosmopolitan.com/newsletter/",
    "https://www.allure.com/newsletter/",
    "https://www.byrdie.com/newsletter/",
    "https://www.manrepeller.com/newsletter/",
    "https://www.stylecaster.com/newsletter/",
    "https://www.thestyleline.com/",
    "https://www.fashionnotes.substack.com/",
    "https://dirt.substack.com/",
    "https://www.sustainablefashionforum.com/newsletter/",

    # ---- Sports ----
    "https://www.espn.com/espn/newsletters",
    "https://www.theathletic.com/newsletters/",
    "https://www.si.com/newsletter/",
    "https://www.bleacherreport.com/newsletter/",
    "https://www.sportingnews.com/newsletter/",
    "https://theathletic.substack.com/",
    "https://www.rotoworld.com/newsletter/",
    "https://www.fantasypros.com/newsletter/",
    "https://www.footballoutsiders.com/newsletter/",
    "https://www.fangraphs.com/newsletter/",
    "https://www.basketball-reference.com/newsletter/",
    "https://www.nfltradeanalysis.net/newsletter/",
    "https://www.defector.com/newsletter/",
    "https://www.fearandblood.com/",
    "https://www.hotreading.substack.com/",
    "https://www.extratime.ie/newsletter/",
    "https://www.theguardian.com/sport/newsletter",
    "https://trainingpeaks.com/newsletter/",
    "https://www.velonews.com/newsletter/",
    "https://www.cyclingnews.com/newsletter/",
    "https://www.trailrunnermag.com/newsletter/",

    # ---- Gaming ----
    "https://www.pcgamer.com/newsletter/",
    "https://www.ign.com/newsletters",
    "https://www.gamespot.com/newsletter/",
    "https://www.polygon.com/newsletter/",
    "https://www.eurogamer.net/newsletter/",
    "https://www.rockpapershotgun.com/newsletter/",
    "https://www.kotaku.com/newsletter/",
    "https://www.gamesradar.com/newsletter/",
    "https://www.destructoid.com/newsletter/",
    "https://www.vg247.com/newsletter/",
    "https://www.pocketgamer.com/newsletter/",
    "https://www.toucharcade.com/newsletter/",
    "https://gamediscoverability.substack.com/",
    "https://www.naavik.co/digest/",
    "https://gamesindustry.biz/newsletters",
    "https://venturebeat.com/category/games/newsletter/",
    "https://mobilegamer.biz/newsletter/",
    "https://www.gamesindustry.biz/newsletter",
    "https://www.gamedevreport.com/",
    "https://howtomarketagame.substack.com/",

    # ---- Film & TV ----
    "https://www.indiewire.com/newsletter/",
    "https://variety.com/newsletter/",
    "https://deadline.com/newsletter/",
    "https://www.hollywoodreporter.com/newsletter/",
    "https://www.screendaily.com/newsletter/",
    "https://www.empireonline.com/newsletter/",
    "https://www.totalfilm.com/newsletter/",
    "https://letterboxd.com/newsletter/",
    "https://www.rogerebert.com/newsletter/",
    "https://www.slashfilm.com/newsletter/",
    "https://www.avclub.com/newsletter/",
    "https://www.vulture.com/newsletter/",
    "https://www.cinemablend.com/newsletter/",
    "https://www.collider.com/newsletter/",
    "https://www.screenrant.com/newsletter/",
    "https://bloody-disgusting.com/newsletter/",
    "https://www.animation magazine.com/newsletter/",
    "https://www.animationcareer.com/newsletter/",
    "https://www.cartoonbrew.com/newsletter/",

    # ---- Music ----
    "https://www.rollingstone.com/newsletter/",
    "https://pitchfork.com/newsletter/",
    "https://www.nme.com/newsletter/",
    "https://www.spin.com/newsletter/",
    "https://www.stereogum.com/newsletter/",
    "https://www.brooklynvegan.com/newsletter/",
    "https://www.consequence.net/newsletter/",
    "https://www.allmusic.com/newsletter/",
    "https://www.musicomh.com/newsletter/",
    "https://loudwire.com/newsletter/",
    "https://www.metalinjection.net/newsletter/",
    "https://www.blabbermouth.net/newsletter/",
    "https://www.jazziz.com/newsletter/",
    "https://www.jazz.fm/newsletter/",
    "https://americansongwriter.com/newsletter/",
    "https://www.countrymusic.com/newsletter/",
    "https://roughstock.com/newsletter/",
    "https://www.rhapsody.com/newsletter/",
    "https://www.bandcamp.com/newsletter/",
    "https://musically.com/newsletter/",
    "https://www.musicbusinessworldwide.com/newsletter/",
    "https://www.hypebot.com/newsletter/",
    "https://www.musicweek.com/newsletter/",

    # ---- Automotive ----
    "https://www.caranddriver.com/newsletter/",
    "https://www.motortrend.com/newsletter/",
    "https://www.roadandtrack.com/newsletter/",
    "https://www.autoblog.com/newsletter/",
    "https://jalopnik.com/newsletter/",
    "https://www.topgear.com/newsletter/",
    "https://www.autocar.co.uk/newsletter/",
    "https://www.autoweek.com/newsletter/",
    "https://www.carbuzz.com/newsletter/",
    "https://www.edmunds.com/newsletter/",
    "https://www.kbb.com/newsletter/",
    "https://www.thedrive.com/newsletter/",
    "https://www.greencarreports.com/newsletter/",
    "https://www.insideevs.com/newsletter/",
    "https://electrek.co/newsletter/",
    "https://www.evspecifications.com/newsletter/",
    "https://teslamotorsclub.substack.com/",
    "https://www.driving.ca/newsletter/",
    "https://www.drivingelectric.com/newsletter/",

    # ---- Personal Development ----
    "https://jamesclear.com/3-2-1",
    "https://www.markmanson.net/newsletter",
    "https://www.brainpickings.org/newsletter/",
    "https://www.tim.blog/newsletter",
    "https://fs.blog/newsletter/",
    "https://www.ryanholiday.net/newsletter/",
    "https://www.juliaevans.com/newsletter/",
    "https://www.nateliason.com/newsletter/",
    "https://www.perell.com/newsletter",
    "https://www.juliacameronlive.com/newsletter/",
    "https://www.paulgraham.com/",
    "https://www.brenebrown.com/newsletter/",
    "https://www.simonsinekworks.com/newsletter/",
    "https://www.dandapani.org/newsletter/",
    "https://www.tonyrobbins.com/newsletter/",
    "https://www.davidgoggins.com/newsletter/",
    "https://www.mel robbins.com/newsletter/",
    "https://www.rubygranger.com/newsletter/",
    "https://www.scotthyoung.com/blog/newsletter/",
    "https://www.calnewport.com/newsletter/",
    "https://www.adamgrant.net/newsletter/",
    "https://radreads.substack.com/",
    "https://www.productiveflourishing.com/newsletter/",
    "https://www.michaelhyatt.com/newsletter/",
    "https://www.brendonburchard.com/newsletter/",
    "https://www.chrisducker.com/newsletter/",
    "https://www.patflynn.com/newsletter/",

    # ---- Humor & Culture ----
    "https://garbage.substack.com/",
    "https://www.mcsweeneys.net/newsletter/",
    "https://www.theonion.com/newsletter/",
    "https://reductress.com/newsletter/",
    "https://thebelladonnascomedy.substack.com/",
    "https://clickhole.com/newsletter/",
    "https://www.someecards.com/newsletter/",
    "https://www.funny-or-die.com/newsletter/",
    "https://lacesout.substack.com/",
    "https://www.cracked.com/newsletter/",
    "https://www.thepoke.co.uk/newsletter/",
    "https://www.thebeaverton.com/newsletter/",
    "https://www.newyorker.com/newsletters/daily-humor",

    # ---- Photography & Visual Arts ----
    "https://petapixel.com/newsletter/",
    "https://fstoppers.com/newsletter/",
    "https://www.dpreview.com/newsletter/",
    "https://www.digitalcameraworld.com/newsletter/",
    "https://www.bhphotovideo.com/find/newsLetter/signUp.jsp",
    "https://www.adorama.com/alc/newsletter/",
    "https://www.photoshelter.com/newsletter/",
    "https://www.smugmug.com/newsletter/",
    "https://www.shootingfilm.net/newsletter/",
    "https://www.lomography.com/newsletter/",
    "https://www.aphotoeditor.com/newsletter/",
    "https://www.a-pblog.com/newsletter/",
    "https://www.lensculture.com/newsletter/",
    "https://www.eyemagazine.com/newsletter/",
    "https://www.artforum.com/newsletter/",
    "https://www.frieze.com/newsletter/",
    "https://www.artnews.com/newsletter/",
    "https://www.artsy.net/newsletter/",
    "https://www.artnet.com/newsletter/",

    # ---- Home & Lifestyle ----
    "https://www.houzz.com/newsletter/",
    "https://www.apartmenttherapy.com/newsletter/",
    "https://www.bhg.com/newsletter/",
    "https://www.housebeautiful.com/newsletter/",
    "https://www.architecturaldigest.com/newsletter/",
    "https://www.thespruce.com/newsletter/",
    "https://www.hunker.com/newsletter/",
    "https://www.designmilk.com/newsletter/",
    "https://www.dezeen.com/newsletter/",
    "https://www.architecturedigest.com/newsletter/",
    "https://www.countryliving.com/newsletter/",
    "https://www.goodhousekeeping.com/newsletter/",
    "https://www.realsimple.com/newsletter/",
    "https://www.marthastewart.com/newsletter/",
    "https://www.domino.com/newsletter/",
    "https://www.mydomaine.com/newsletter/",
    "https://www.elledecor.com/newsletter/",
    "https://www.lonny.com/newsletter/",

    # ---- Pets ----
    "https://www.akc.org/newsletter/",
    "https://www.aspca.org/newsletter/",
    "https://www.petfinder.com/newsletter/",
    "https://www.dogster.com/newsletter/",
    "https://www.catster.com/newsletter/",
    "https://www.petmd.com/newsletter/",
    "https://www.thesprucepets.com/newsletter/",
    "https://www.whole-dog-journal.com/newsletter/",
    "https://www.moderndogmagazine.com/newsletter/",
    "https://www.catnipnewsletter.com/",
    "https://www.dogtipper.com/newsletter/",
    "https://fearfreehappyhomes.com/newsletter/",
    "https://www.vetstreet.com/newsletter/",

    # ---- DIY & Crafts ----
    "https://www.instructables.com/newsletter/",
    "https://www.familyhandyman.com/newsletter/",
    "https://www.thisoldhouse.com/newsletter/",
    "https://www.ravelry.com/newsletter/",
    "https://www.craftsy.com/newsletter/",
    "https://www.creativebug.com/newsletter/",
    "https://www.sewmag.co.uk/newsletter/",
    "https://www.loveknitting.com/newsletter/",
    "https://www.weallsew.com/newsletter/",
    "https://www.thimbleandthorn.com/newsletter/",
    "https://www.woodsmith.com/newsletter/",
    "https://www.woodworkingnetwork.com/newsletter/",
    "https://www.popularwoodworking.com/newsletter/",
    "https://www.finewoodworking.com/newsletter/",
    "https://www.gardenersworld.com/newsletter/",
    "https://www.rhs.org.uk/newsletter",
    "https://www.bhg.com/gardening/newsletter/",
    "https://gardeningknowhow.com/newsletter/",

    # ---- Nonprofit & Social Impact ----
    "https://www.ssireview.org/newsletter/",
    "https://www.nonprofitquarterly.org/newsletter/",
    "https://www.charitynavigator.org/newsletter/",
    "https://www.networkforgood.com/newsletter/",
    "https://www.boardsource.org/newsletter/",
    "https://www.grantspace.org/newsletter/",
    "https://www.candid.org/newsletter/",
    "https://www.globalgiving.org/newsletter/",
    "https://www.idealist.org/newsletter/",
    "https://www.catchafire.org/newsletter/",
    "https://www.volunteermatch.org/newsletter/",
    "https://www.dosomething.org/newsletter/",

    # ---- Productivity & Tools ----
    "https://www.productivitygame.com/newsletter/",
    "https://www.getabstract.com/newsletter/",
    "https://www.lifehacker.com/newsletter/",
    "https://www.asinofsomewhere.com/",
    "https://www.bakadesuyo.com/newsletter/",
    "https://www.fortelabs.com/newsletter/",
    "https://www.buildingasecondbrain.com/newsletter/",
    "https://www.roamresearch.com/newsletter/",
    "https://www.obsidian.md/newsletter/",
    "https://www.notion.so/newsletter/",
    "https://www.taskade.com/newsletter/",
    "https://www.toggl.com/newsletter/",
    "https://www.rescuetime.com/newsletter/",
    "https://every.to/",
    "https://superorganizers.substack.com/",
    "https://www.workingtheorys.substack.com/",
    "https://www.howtheycreate.com/",
]

async def subscribe_to_newsletter(page: Page, profile_dict: dict):
    """
    Navigates to a standardized newsletter page and inputs the bot's email.
    Guarantees inbound email traffic to warm the Gmail inbox.
    """
    persona_name = profile_dict.get("persona", {}).get("name", "UnknownBot")
    
    # IMPORTANT: Your database must pass the bot's email address in the profile_dict!
    bot_email = profile_dict.get("email") 
    
    if not bot_email:
        log.error(f"❌ [{persona_name}] No email address found in database profile! Skipping newsletter.")
        return
    target_url = random.choice(NEWSLETTER_URLS)
    log.info(f"📧 [{persona_name}] Attempting newsletter signup at: {target_url}")
    try:
        await page.goto(target_url, timeout=60000, wait_until="domcontentloaded")
        await asyncio.sleep(random.uniform(3.0, 6.0))
        # Scroll a bit to make the pop-ups or inline forms appear
        await page.mouse.wheel(0, random.randint(300, 700))
        await asyncio.sleep(random.uniform(2.0, 4.0))
        # THE MAGIC LOCATOR: Almost all web developers use type="email" or name="email" 
        email_input = page.locator('input[type="email"], input[name="email"], input[placeholder*="email" i]').first
        
        # Check if the input box actually exists on the page
        if await email_input.is_visible(timeout=5000):
            log.info(f"⌨️ [{persona_name}] Found email box. Typing {bot_email}...")
            
            # Click the box and type it like a human
            await email_input.click()
            await asyncio.sleep(random.uniform(0.5, 1.5))
            
            # Type the email with a slight delay between keystrokes
            await email_input.fill(bot_email)
            await asyncio.sleep(random.uniform(1.0, 2.0))
            
            # Hit Enter to submit the form!
            log.info(f"🖱️ [{persona_name}] Submitting email...")
            await page.keyboard.press("Enter")
            
            # Wait to let the "Success!" screen load
            await asyncio.sleep(random.uniform(4.0, 7.0))
            log.info(f"✅ [{persona_name}] Successfully subscribed to newsletter!")
            
        else:
            log.warning(f"⚠️ [{persona_name}] Could not find the email input box on this site.")
    except Exception as e:
        log.error(f"❌ [{persona_name}] Failed to subscribe to newsletter: {e}")