"""
seed_supabase.py
----------------
Run this ONCE to push your 7 profiles into your new Supabase database.
Includes the new 'email' column and a massive, randomized Topic Matrix.
"""
import os
import random
from pathlib import Path
from dotenv import load_dotenv
from supabase import create_client, Client

# Load .env file
load_dotenv(dotenv_path=Path(__file__).parent / ".env")

# 1. Connect to Supabase
url: str = os.getenv("SUPABASE_URL")
key: str = os.getenv("SUPABASE_KEY")
if not url or not key:
    raise ValueError("Missing SUPABASE_URL or SUPABASE_KEY in .env")
    
supabase: Client = create_client(url, key)

def _pid(n: int) -> str:
    # Pulls the MLX IDs from your existing .env file
    return os.getenv(f"PROFILE_{n}", f"fallback-id-{n}").strip()

# ==========================================
# 🧠 MASSIVE TOPIC MATRIX
# ==========================================
# Instead of hardcoding 5 topics per bot, we randomly assign them 4 topics 
# from this giant list so they develop unique, permanent interests.

MASTER_TOPICS = [

    # ---- Personal Finance & Money ----
    "personal finance and budgeting",
    "how to save money on groceries",
    "best high yield savings accounts 2026",
    "how to get out of credit card debt",
    "building an emergency fund from scratch",
    "zero based budgeting method explained",
    "how to negotiate a salary raise",
    "passive income ideas that actually work",
    "side hustles to make extra money",
    "how to file taxes as a freelancer",
    "understanding your credit score",
    "how to dispute errors on credit report",
    "best cashback credit cards",
    "money saving apps worth using",
    "frugal living tips for families",
    "how to live below your means",
    "envelope budgeting system tutorial",
    "how to afford a house on one income",
    "tips for saving for a down payment",
    "how to stop impulse buying",

    # ---- Investing & Wealth Building ----
    "how to invest in index funds",
    "how to start investing with little money",
    "best dividend stocks for beginners",
    "understanding the stock market basics",
    "Roth IRA vs traditional IRA explained",
    "how to max out your 401k",
    "compound interest explained simply",
    "dollar cost averaging strategy",
    "how to read a stock chart",
    "best ETFs for long term investing",
    "how to invest in real estate with no money",
    "REITs explained for beginners",
    "house hacking strategy for first time buyers",
    "BRRRR method real estate investing",
    "how to analyze a rental property",
    "best robo advisors for beginners",
    "how to build a dividend portfolio",
    "value investing strategy explained",
    "growth stocks vs value stocks",
    "how to invest in bonds",
    "options trading basics for beginners",
    "how to hedge your portfolio",
    "portfolio diversification strategies",

    # ---- Cryptocurrency & Web3 ----
    "cryptocurrency trading for beginners",
    "how to buy Bitcoin safely",
    "best crypto exchanges to use",
    "what is Ethereum and how does it work",
    "DeFi explained for beginners",
    "how to stake cryptocurrency",
    "NFT investing risks and rewards",
    "what is a crypto wallet",
    "cold storage crypto security tips",
    "how to avoid crypto scams",
    "altcoin investing strategies",
    "crypto tax rules you need to know",
    "how to read crypto charts",
    "what is blockchain technology",
    "Solana vs Ethereum comparison",
    "best crypto YouTube channels to follow",
    "how to use a DEX decentralized exchange",
    "yield farming explained",
    "what is a DAO and how to join one",
    "crypto portfolio rebalancing tips",

    # ---- Technology & Gadgets ----
    "best gaming laptops 2026",
    "how to build a custom PC step by step",
    "latest AI software tools for productivity",
    "best budget smartphones this year",
    "how to speed up your old laptop",
    "top smart home devices worth buying",
    "best mechanical keyboards for typing",
    "ultrawide monitor pros and cons",
    "best wireless earbuds under 100",
    "how to set up a home media server",
    "best password managers reviewed",
    "VPN explained and why you need one",
    "how to protect your privacy online",
    "best antivirus software 2026",
    "how to set up a NAS drive at home",
    "best standing desks for home office",
    "how to improve your home Wi-Fi signal",
    "mesh wifi systems compared",
    "best webcams for video calls",
    "smart TV buying guide 2026",
    "how to block ads on all devices",
    "best e-readers compared",
    "tablet vs laptop which is better",
    "best drawing tablets for artists",
    "how to set up dual monitors",

    # ---- Software & Apps ----
    "best productivity apps for iPhone",
    "best Android apps you should download",
    "how to use Notion for beginners",
    "Obsidian vs Notion for note taking",
    "best project management tools for teams",
    "how to use ChatGPT effectively",
    "best AI writing tools compared",
    "how to use Google Sheets like a pro",
    "Excel tips and tricks for beginners",
    "best free video editing software",
    "how to edit videos on a phone",
    "best photo editing apps for free",
    "how to use Lightroom for beginners",
    "best screen recording software",
    "how to automate repetitive tasks",
    "Zapier vs Make automation tools",
    "best time tracking apps for freelancers",
    "how to use Trello for project management",
    "best browser extensions for productivity",
    "how to clean up your digital life",

    # ---- Programming & Development ----
    "Python programming for beginners",
    "JavaScript fundamentals explained",
    "how to build your first website",
    "HTML and CSS beginner tutorial",
    "React vs Vue which to learn first",
    "how to learn web development for free",
    "best coding bootcamps worth it",
    "how to get your first developer job",
    "Git and GitHub basics tutorial",
    "how to build a REST API",
    "SQL for beginners full tutorial",
    "how to scrape websites with Python",
    "building a Discord bot from scratch",
    "Docker explained for beginners",
    "Linux command line basics",
    "how to deploy a website for free",
    "Raspberry Pi projects for beginners",
    "how to build a Chrome extension",
    "TypeScript vs JavaScript comparison",
    "best resources to learn programming free",
    "how to build a mobile app from scratch",
    "Swift programming basics for iOS",
    "Flutter vs React Native comparison",
    "how to host a website on AWS",
    "serverless architecture explained",

    # ---- Artificial Intelligence ----
    "how AI is changing the job market",
    "best AI tools for small businesses",
    "how to use AI for content creation",
    "prompt engineering tips and tricks",
    "how to build a chatbot with AI",
    "machine learning basics explained",
    "how neural networks work simply",
    "AI image generation tools compared",
    "using AI for video editing",
    "best AI coding assistants",
    "how to use AI for email writing",
    "AI tools for designers and artists",
    "how to automate your business with AI",
    "risks of artificial intelligence",
    "future of AI in healthcare",
    "AI tools for students and studying",
    "how to detect AI generated content",
    "best AI search engines",
    "using AI for social media marketing",
    "open source AI models explained",

    # ---- Gaming ----
    "best RPG games to play in 2026",
    "top free to play games on PC",
    "how to get better at FPS games",
    "best gaming headsets for PC",
    "how to build a gaming PC under 1000",
    "PS5 vs Xbox Series X comparison",
    "best indie games you missed",
    "how to stream on Twitch for beginners",
    "best open world games ever made",
    "how to make money playing games",
    "gaming chair vs regular office chair",
    "best controller for PC gaming",
    "how to reduce input lag while gaming",
    "Minecraft building tips and tricks",
    "best strategy games for beginners",
    "retro gaming consoles worth buying",
    "how to emulate old games legally",
    "best couch co-op games for couples",
    "how to improve internet for gaming",
    "best gaming monitors for fast games",

    # ---- Food & Cooking ----
    "easy 30 minute dinner recipes",
    "meal prep ideas for the whole week",
    "authentic Italian pasta from scratch",
    "how to cook perfect steak at home",
    "beginner baking tips for bread",
    "how to make homemade pizza dough",
    "high protein meal prep for gym",
    "vegetarian dinner ideas for family",
    "how to cook with cast iron skillet",
    "air fryer recipes beginners love",
    "how to make sourdough bread starter",
    "Asian stir fry sauces to master",
    "how to meal plan on a budget",
    "slow cooker recipes for busy nights",
    "how to properly season a cast iron pan",
    "beginner sushi making at home",
    "authentic Thai curry from scratch",
    "how to make dumplings from scratch",
    "best kitchen knives for home cooks",
    "knife sharpening techniques at home",
    "how to make restaurant quality sauces",
    "fermented foods you can make at home",
    "how to make stock from scraps",
    "batch cooking for the whole month",
    "easy desserts for dinner parties",
    "how to bake French croissants",
    "best cookbooks for beginners",
    "how to pair wine with food",
    "how to host a dinner party stress free",
    "spices every kitchen needs",

    # ---- Health & Fitness ----
    "home workout routines no equipment needed",
    "how to start running for beginners",
    "marathon training plan for beginners",
    "best protein sources for building muscle",
    "how to lose belly fat with exercise",
    "intermittent fasting beginners guide",
    "HIIT workout routine for weight loss",
    "yoga poses for lower back pain",
    "how to improve flexibility fast",
    "swimming technique tips for beginners",
    "best supplements for muscle recovery",
    "how to track macros for fat loss",
    "progressive overload explained simply",
    "how to stay consistent with workouts",
    "gym beginner mistakes to avoid",
    "how to do a pull up from scratch",
    "best pre workout foods for energy",
    "cold shower benefits explained",
    "how to improve your VO2 max",
    "heart rate zones for fat burning",
    "how to prevent running injuries",
    "foam rolling techniques for recovery",
    "best fitness trackers this year",
    "how to build a home gym cheap",
    "strength training for women beginners",
    "powerlifting basics for beginners",
    "kettlebell workout for total body",
    "how to improve posture at your desk",
    "best stretches before and after workout",
    "how to stay active with a desk job",

    # ---- Mental Health & Wellness ----
    "mindfulness and meditation tips for beginners",
    "how to manage anxiety naturally",
    "breathing exercises for stress relief",
    "how to improve sleep quality fast",
    "journaling for mental health benefits",
    "how to build a morning routine",
    "evening routine for better sleep",
    "how to practice gratitude daily",
    "signs of burnout and how to recover",
    "digital detox tips for mental clarity",
    "how to stop overthinking everything",
    "therapy vs self help which to choose",
    "best books on emotional intelligence",
    "how to set healthy boundaries",
    "how to overcome social anxiety",
    "habits of mentally strong people",
    "how to build self confidence",
    "dopamine detox explained and benefits",
    "how to find purpose and meaning in life",
    "how to deal with loneliness as adult",

    # ---- Diet & Nutrition ----
    "keto diet beginner meal plan",
    "Mediterranean diet benefits and foods",
    "vegan diet protein sources guide",
    "how to eat healthy on a tight budget",
    "foods that boost your energy naturally",
    "best anti inflammatory foods to eat",
    "how much protein do I actually need",
    "gut health foods for digestion",
    "how to read nutrition labels correctly",
    "best meal replacement shakes reviewed",
    "calorie deficit explained for weight loss",
    "how to reduce sugar in your diet",
    "gluten free diet complete guide",
    "paleo diet food list and benefits",
    "carnivore diet results and risks",
    "whole30 diet rules and meal ideas",
    "best foods for brain health and focus",
    "how to eat for better skin",
    "superfoods that are actually worth it",
    "vitamin D deficiency signs and fixes",

    # ---- Automotive ----
    "how to change your own car oil",
    "best used cars under 15k to buy",
    "how to negotiate at a car dealership",
    "electric vehicle buying guide 2026",
    "Tesla Model 3 vs Model Y comparison",
    "how to check a used car before buying",
    "car maintenance schedule you should follow",
    "how to change a flat tire safely",
    "best car insurance companies compared",
    "how to lower your car insurance rate",
    "how to detail your car at home",
    "ceramic coating vs wax for your car",
    "best dash cams to buy this year",
    "how to jump start a dead battery",
    "basic car repairs you can do yourself",
    "best budget cars for new drivers",
    "hybrid vs fully electric car pros cons",
    "how to improve fuel economy",
    "best tires for winter driving",
    "how to install a car stereo yourself",

    # ---- Home & DIY ----
    "DIY home plumbing fixes for beginners",
    "how to unclog a stubborn drain",
    "woodworking projects for complete beginners",
    "how to hang shelves without studs",
    "painting a room tips and tricks",
    "how to tile a bathroom floor yourself",
    "best power tools for homeowners",
    "how to fix drywall holes",
    "home electrical basics for DIYers",
    "how to replace a light switch",
    "landscaping ideas for small backyards",
    "how to build raised garden beds",
    "backyard deck building for beginners",
    "how to install laminate flooring",
    "how to fix squeaky floors",
    "how to insulate your home cheaply",
    "smart home devices worth installing",
    "how to reduce your electricity bill",
    "window weatherproofing for winter",
    "how to organize a garage on a budget",
    "decluttering your home room by room",
    "how to deep clean your whole house",
    "best cordless drills reviewed 2026",
    "how to build a shed from scratch",
    "fence building tips and costs",

    # ---- Travel ----
    "backpacking Europe on a tight budget",
    "best hidden beaches in the US",
    "how to travel full time and work remotely",
    "cheapest countries to visit in 2026",
    "how to find cheap flights last minute",
    "best travel credit cards for rewards",
    "how to pack light for any trip",
    "solo travel safety tips for beginners",
    "best travel insurance companies",
    "digital nomad visa countries list",
    "best hostels vs hotels which to choose",
    "how to get TSA Precheck and Global Entry",
    "best travel apps for offline maps",
    "Southeast Asia budget travel guide",
    "Japan travel tips first time visitors",
    "road trip essentials packing list",
    "how to avoid tourist traps abroad",
    "best places to visit in South America",
    "travel hacking points and miles guide",
    "how to work and travel as a freelancer",
    "van life beginner guide and costs",
    "how to find free accommodation abroad",
    "best countries for solo female travel",
    "how to get free hotel upgrades",
    "travel photography tips for beginners",

    # ---- Photography ----
    "photography tips for absolute beginners",
    "best cameras for beginners 2026",
    "mirrorless vs DSLR which to buy",
    "how to shoot in manual mode",
    "aperture shutter speed ISO explained",
    "best lenses for portrait photography",
    "landscape photography tips and settings",
    "how to edit photos in Lightroom",
    "street photography tips for shy people",
    "how to shoot in low light conditions",
    "best photo editing software free",
    "how to take better photos with iPhone",
    "product photography at home setup",
    "food photography lighting tips",
    "how to build a photography portfolio",
    "how to sell stock photos online",
    "real estate photography guide",
    "how to shoot golden hour portraits",
    "astrophotography setup for beginners",
    "how to clean your camera lens properly",

    # ---- Pets & Animals ----
    "how to train a puppy basic commands",
    "best dog food for large breeds",
    "cat behavior explained for owners",
    "how to introduce a new cat to your home",
    "best low maintenance pets for apartments",
    "how to care for a bearded dragon",
    "freshwater aquarium setup beginner guide",
    "rabbit care guide for new owners",
    "bird care tips for first time owners",
    "how to groom a dog at home",
    "dog separation anxiety solutions",
    "how to stop a dog from barking",
    "best flea treatments for cats and dogs",
    "exotic pets that are legal to own",
    "how to keep outdoor cats safe",
    "best pet insurance companies reviewed",
    "how to make homemade dog treats",
    "dog breeds for first time owners",
    "signs your cat is sick and what to do",
    "how to socialize a rescue dog",

    # ---- Plants & Gardening ----
    "indoor plant care tips for beginners",
    "best houseplants that are hard to kill",
    "how to propagate succulents",
    "vegetable garden for complete beginners",
    "composting at home step by step",
    "how to grow tomatoes in containers",
    "best herbs to grow on a windowsill",
    "how to revive a dying houseplant",
    "hydroponic gardening at home guide",
    "permaculture basics for home gardens",
    "how to get rid of garden pests naturally",
    "best soil mix for raised garden beds",
    "how to grow strawberries at home",
    "seasonal planting guide for beginners",
    "how to grow food in a small apartment",
    "orchid care tips for beginners",
    "how to care for a fiddle leaf fig",
    "best plants for air purification",
    "how to start a wildflower garden",
    "water features for backyard gardens",

    # ---- Books & Literature ----
    "best fiction books of 2025 and 2026",
    "must read classic novels for adults",
    "best self help books that actually work",
    "sci fi books for people who hate sci fi",
    "best mystery and thriller novels 2026",
    "history books that read like stories",
    "how to read more books consistently",
    "best audiobook apps and subscriptions",
    "best biographies and memoirs to read",
    "how to build a reading habit",
    "best books on psychology and behavior",
    "fantasy book series to binge read",
    "best non fiction books for entrepreneurs",
    "book clubs worth joining online",
    "how to annotate books effectively",
    "best philosophy books for beginners",
    "political books everyone should read",
    "best books on stoicism and resilience",
    "graphic novels for adults recommended",
    "books recommended by famous CEOs",

    # ---- Movies & TV ----
    "best movies to watch on Netflix 2026",
    "underrated films worth streaming now",
    "best TV shows to binge watch this year",
    "classic movies everyone should see",
    "best documentary series on streaming",
    "how to find obscure foreign films",
    "best animated movies for adults",
    "horror movies that will actually scare you",
    "best true crime documentaries",
    "movies based on true stories",
    "best sci fi shows for non sci fi fans",
    "how to watch every Marvel movie in order",
    "best stand up comedy specials",
    "foreign language films that won awards",
    "best heist movies of all time",
    "movies with the best plot twists",
    "best war movies based on real events",
    "award winning short films to watch",
    "best westerns to watch for beginners",
    "cinematic masterpieces from the 70s",

    # ---- Music ----
    "how to start learning guitar as adult",
    "best beginner acoustic guitars",
    "piano lessons for complete beginners",
    "how to produce music at home free",
    "best DAW software for music production",
    "music theory basics everyone should know",
    "how to mix and master your own tracks",
    "best microphones for home recording",
    "vinyl record collecting beginner guide",
    "how to read sheet music for beginners",
    "how to improve your singing voice",
    "best headphones for music listening",
    "how to build a home recording studio",
    "jazz music history and best artists",
    "how to DJ for complete beginners",
    "best music streaming services compared",
    "how to get your music on Spotify",
    "best music podcasts to listen to",
    "classical music guide for beginners",
    "how to write your first song",

    # ---- History ----
    "history of the Roman Empire rise and fall",
    "World War II causes and consequences",
    "ancient Egyptian civilization explained",
    "history of the Cold War simplified",
    "the real history of the Viking age",
    "how the Industrial Revolution changed the world",
    "history of the Silk Road and trade",
    "ancient Greek civilization and legacy",
    "history of the Byzantine Empire",
    "how the Mongol Empire conquered the world",
    "history of slavery in America",
    "the French Revolution explained simply",
    "history of the Ottoman Empire",
    "how ancient Rome influenced modern law",
    "history of the civil rights movement",
    "ancient Mayan civilization facts",
    "history of the British Empire",
    "how the Renaissance changed art and science",
    "history of early America and colonization",
    "the real story of the crusades",

    # ---- Science ----
    "how black holes form and work",
    "quantum physics explained for beginners",
    "how vaccines work in your body",
    "what causes climate change explained",
    "how evolution really works",
    "the human genome project explained",
    "how CRISPR gene editing works",
    "what is dark matter and dark energy",
    "how the immune system works",
    "the science of sleep explained",
    "how nuclear reactors generate power",
    "how earthquakes and tsunamis form",
    "what causes inflation in economics",
    "how the brain processes emotions",
    "the science behind addiction",
    "how to read a scientific study",
    "big bang theory explained simply",
    "how GPS satellites work",
    "the science of habit formation",
    "how the internet physically works",

    # ---- Space & Astronomy ----
    "how to start stargazing as a beginner",
    "best telescopes for beginners 2026",
    "SpaceX Starship mission updates",
    "how to photograph the Milky Way",
    "best astronomy apps for night sky",
    "life on Mars latest discoveries",
    "how to see the Northern Lights",
    "nearest exoplanets that could support life",
    "James Webb telescope latest images",
    "how the International Space Station works",
    "history of the Apollo moon missions",
    "what would happen if the sun disappeared",
    "how to track satellites in real time",
    "asteroid threats and planetary defense",
    "how long to travel to other planets",

    # ---- Philosophy & Psychology ----
    "stoicism philosophy practical guide",
    "existentialism explained for beginners",
    "how to think more rationally",
    "cognitive biases that affect decisions",
    "Jungian psychology concepts explained",
    "how to practice Stoic daily exercises",
    "philosophy of meaning and happiness",
    "the trolley problem and ethics",
    "how to argue better and more logically",
    "Plato vs Aristotle key differences",
    "philosophy of consciousness explained",
    "best philosophers to read first",
    "how Buddhism views suffering",
    "practical philosophy for daily life",
    "what is epistemology and why it matters",
    "social psychology experiments explained",
    "Milgram obedience study and lessons",
    "how propaganda works psychologically",
    "narcissism signs and how to respond",
    "attachment theory explained simply",

    # ---- Language Learning ----
    "how to learn a new language fast",
    "best apps to learn Spanish 2026",
    "how to become fluent in French",
    "Japanese for beginners where to start",
    "learning Mandarin Chinese basics",
    "how immersion language learning works",
    "best podcasts for learning German",
    "tips for learning vocabulary quickly",
    "how to learn Korean with K-dramas",
    "language exchange apps and websites",
    "how to practice speaking a new language",
    "memory techniques for vocabulary",
    "best YouTube channels for learning languages",
    "how to pass a TOEFL exam",
    "Italian phrases every traveler needs",
    "how long does it take to learn a language",
    "Arabic for beginners starter guide",
    "how to keep a language after learning it",
    "sign language basics for beginners",
    "best language learning books",

    # ---- Fashion & Style ----
    "how to build a capsule wardrobe",
    "men's style basics for beginners",
    "how to dress well on a budget",
    "sustainable fashion brands worth buying",
    "how to thrift shop like a pro",
    "color coordination tips for outfits",
    "best clothing brands for quality",
    "how to care for expensive clothes",
    "women's minimalist wardrobe guide",
    "how to find your personal style",
    "best sneakers for everyday wear 2026",
    "how to style oversized clothing",
    "hair care routine for damaged hair",
    "skincare routine for oily skin",
    "best drugstore skincare products",
    "how to do a full face of makeup as beginner",
    "natural hair care tips for growth",
    "men's grooming routine basics",
    "how to iron and care for dress shirts",
    "how to shop smarter not more",

    # ---- Career & Work ----
    "how to write a resume that gets noticed",
    "best ways to find remote work in 2026",
    "how to ace a job interview",
    "negotiating your first salary offer",
    "how to switch careers at 30 or 40",
    "how to ask for a promotion",
    "best LinkedIn profile tips",
    "how to network when you hate networking",
    "freelancing guide how to find first clients",
    "how to manage work from home productivity",
    "how to deal with a toxic workplace",
    "emotional intelligence at work tips",
    "how to set professional goals",
    "building a personal brand online",
    "how to become a consultant in your field",
    "best certifications to boost your career",
    "how to work less and earn more",
    "career change to UX design guide",
    "how to get promoted faster",
    "remote job boards you should know",

    # ---- Entrepreneurship & Business ----
    "how to start a business with no money",
    "best small business ideas for 2026",
    "how to write a simple business plan",
    "dropshipping for beginners guide",
    "how to start a print on demand store",
    "Etsy shop setup for beginners",
    "how to start a podcast from scratch",
    "YouTube channel monetization guide",
    "how to build an online course",
    "email list building from zero",
    "how to find your business niche",
    "Amazon FBA beginner guide",
    "how to flip items for profit",
    "starting a cleaning business guide",
    "how to open a food truck business",
    "how to sell digital products online",
    "how to start a blog and make money",
    "affiliate marketing for beginners",
    "how to grow a social media account",
    "solopreneur business ideas that scale",

    # ---- Marketing & Social Media ----
    "how to grow on Instagram organically",
    "TikTok marketing strategy for businesses",
    "how to run Facebook ads for beginners",
    "content calendar how to plan your posts",
    "how to write viral headlines",
    "email marketing beginner guide",
    "how to do SEO for your website",
    "Google Analytics explained for beginners",
    "how to grow a YouTube channel from zero",
    "Pinterest marketing for bloggers",
    "how to use LinkedIn for B2B marketing",
    "how to write compelling product descriptions",
    "social media content ideas for small business",
    "how to build a brand from nothing",
    "podcast marketing strategies",
    "how to get press coverage for free",
    "copywriting tips that increase sales",
    "how to create a viral marketing campaign",
    "influencer marketing guide for brands",
    "how to repurpose content across platforms",

    # ---- Education & Studying ----
    "how to study effectively for exams",
    "best study techniques backed by science",
    "how to take better notes in class",
    "Pomodoro technique how it works",
    "how to memorize information faster",
    "best ways to learn anything quickly",
    "how to read faster and retain more",
    "Anki flashcard system explained",
    "how to focus when you cannot concentrate",
    "building a self directed learning routine",
    "best free online learning platforms",
    "how to get a college degree online cheap",
    "learning styles myth debunked",
    "how to stay motivated while studying",
    "best YouTube channels for learning",
    "how to learn new skills faster",
    "spaced repetition learning technique",
    "mind mapping for studying guide",
    "how to write a research paper fast",
    "college survival tips for freshmen",

    # ---- Relationships & Social ----
    "how to make new friends as an adult",
    "communication tips for couples",
    "how to improve your listening skills",
    "how to deal with difficult people",
    "setting healthy boundaries in relationships",
    "how to recover from a breakup",
    "how to be more charismatic",
    "long distance relationship tips",
    "how to stop people pleasing",
    "signs of a toxic relationship",
    "how to have difficult conversations",
    "building deeper friendships",
    "how to be less awkward in social situations",
    "how to support someone with depression",
    "how to be a better partner",
    "how to improve your body language",
    "tips for building trust in relationships",
    "how to forgive someone who hurt you",
    "how to get over social anxiety",
    "healthy conflict resolution strategies",

    # ---- Parenting & Family ----
    "newborn sleep schedule tips for parents",
    "how to raise confident children",
    "screen time limits for kids by age",
    "how to talk to teenagers about hard topics",
    "positive discipline techniques for toddlers",
    "how to help kids with anxiety",
    "activities to do with toddlers at home",
    "how to raise emotionally intelligent children",
    "balancing work and parenting at home",
    "how to set up a kids bedroom",
    "how to save for college as a parent",
    "teaching kids about money early",
    "how to handle sibling rivalry",
    "home schooling basics for beginners",
    "after school routines that actually work",
    "helping kids adjust to divorce",
    "best educational toys for different ages",
    "how to read to children for better brain development",
    "nutrition tips for picky eating children",
    "how to raise bilingual children",

    # ---- Law & Legal ----
    "how to write a basic will yourself",
    "tenant rights you should know",
    "how to handle a small claims court case",
    "what to do if you get a DUI",
    "how to copyright your creative work",
    "LLC vs sole proprietorship for freelancers",
    "how to trademark your business name",
    "workplace discrimination laws explained",
    "how to deal with debt collectors legally",
    "what happens during a bankruptcy filing",
    "how to fight a traffic ticket",
    "understanding GDPR for small businesses",
    "landlord rights and tenant laws by state",
    "how to negotiate a legal settlement",
    "basics of contract law for freelancers",

    # ---- Environment & Sustainability ----
    "how to live a more sustainable life",
    "zero waste lifestyle beginner guide",
    "how to reduce your carbon footprint",
    "best reusable products to switch to",
    "composting at home for beginners",
    "how to start recycling properly",
    "solar panels for home worth the cost",
    "how to grow your own food at home",
    "sustainable fashion brands guide",
    "how electric vehicles help the environment",
    "climate change solutions that work",
    "how to reduce plastic use at home",
    "water conservation tips for homeowners",
    "vegan diet environmental impact",
    "how to make your home more energy efficient",
    "best eco friendly cleaning products",
    "how to offset your carbon footprint",
    "rewilding your backyard for wildlife",
    "how to support local food systems",
    "plastic pollution facts and what you can do",

    # ---- Outdoor & Adventure ----
    "beginner hiking tips and gear list",
    "how to start backpacking overnight",
    "best national parks to visit in the US",
    "rock climbing for beginners guide",
    "how to camp without experience",
    "best camping gear under 200 dollars",
    "how to read a topographic map",
    "wilderness survival skills basics",
    "fishing for beginners gear and tips",
    "how to kayak and canoe for beginners",
    "mountain biking trails for beginners",
    "how to train for your first hike",
    "surfing for complete beginners",
    "skiing for beginners tips and gear",
    "best outdoor cooking gear for camping",
    "how to start trail running",
    "wild swimming safety tips",
    "how to navigate without a phone",
    "foraging wild edible plants safely",
    "building a campfire safely",

    # ---- Crafts & Hobbies ----
    "how to start crocheting for beginners",
    "knitting basics complete starter guide",
    "acrylic painting techniques for beginners",
    "how to start watercolor painting",
    "candle making at home beginner guide",
    "how to make homemade soap",
    "resin art for beginners guide",
    "leather working basics at home",
    "how to start embroidery",
    "calligraphy for beginners starter kit",
    "how to do macrame for home decor",
    "paper crafting and origami basics",
    "pottery and clay at home guide",
    "how to start drawing as adult beginner",
    "digital illustration for beginners",
    "how to get into model trains hobby",
    "amateur radio ham radio beginner guide",
    "how to start collecting vintage items",
    "card making and scrapbooking",
    "how to start beekeeping at home",

    # ---- Real Estate ----
    "first time home buyer complete guide",
    "how to negotiate a home purchase",
    "mortgage types explained for beginners",
    "what is a home inspection and why it matters",
    "how to invest in real estate with 10k",
    "best cities to invest in real estate 2026",
    "how to find off market properties",
    "short term rental investing guide",
    "how to screen tenants for rental property",
    "property management tips for landlords",
    "how to raise rent without losing tenants",
    "1031 exchange explained for investors",
    "cap rate and cash on cash return explained",
    "how to flip a house step by step",
    "wholesaling real estate explained",

    # ---- Politics & Current Events ----
    "how the US electoral college works",
    "how to read the news critically",
    "immigration policy debate explained",
    "how does the Federal Reserve work",
    "climate change policy around the world",
    "how universal basic income works",
    "healthcare systems US vs other countries",
    "what is modern monetary theory",
    "how propaganda works in modern media",
    "how to spot misinformation online",
    "gun control debate both sides",
    "history of US foreign policy",
    "how the UN actually works",
    "social media censorship debate",
    "how to be politically informed without stress",

    # ---- Spirituality & Religion ----
    "Buddhism basics for non Buddhists",
    "how mindfulness connects to meditation",
    "stoicism as a practical spiritual practice",
    "introduction to Taoism philosophy",
    "yoga philosophy beyond the poses",
    "how to start a daily meditation habit",
    "manifestation and law of attraction explained",
    "numerology basics for beginners",
    "astrology birth chart beginner guide",
    "crystals and their claimed meanings",
    "how to practice gratitude spiritually",
    "history and basics of Hinduism",
    "differences between world religions",
    "near death experience science and stories",
    "journaling as a spiritual practice",

    # ---- Food Science & Special Diets ----
    "what actually happens during digestion",
    "how food affects your mood and brain",
    "best foods to eat for longevity",
    "FODMAP diet explained and food list",
    "how to cook for someone with allergies",
    "anti candida diet food list",
    "low histamine diet guide",
    "AIP autoimmune protocol diet basics",
    "how to cook healthy with no time",
    "best meal delivery services reviewed",
    "how to make healthy food taste good",
    "food label reading complete guide",
    "how to reduce food waste at home",
    "seasonal eating guide by region",
    "fermentation and gut health connection",
]

def get_random_topics(count=4):
    """Picks random, permanent interests for the bot's database profile."""
    return random.sample(MASTER_TOPICS, count)

# ==========================================
# 👤 THE 7 MASTER PROFILES
# ==========================================
PROFILES_TO_UPLOAD = [
    {
        "id": "sarah_nyc",
        "mlx_profile_id": _pid(1),
        "email": "sarah.nyc.automation@gmail.com", # <--- NEW: Crucial for Newsletters
        "persona": {"name": "Sarah", "age": 34, "city": "New York"},
        "browser": {"timezone": "America/New_York", "locale": "en-US", "viewport": {"width": 1440, "height": 900}},
        "behavior": {
            "wpm_range": (70, 95), "typo_rate": 0.02, "typo_correction_delay": (150, 400),
            "scroll_chunk": (200, 450), "scroll_sessions": (2, 4), "back_scroll_chance": 0.05,
            "read_pause_range": (4, 10), "idle_drift_chance": 0.25, "pre_click_hover_ms": (80, 200),
            "result_position_weights": [7, 5, 3, 2, 1, 1, 1, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "marcus_austin",
        "mlx_profile_id": _pid(2),
        "email": "marcus.codes.tx@gmail.com",
        "persona": {"name": "Marcus", "age": 22, "city": "Austin"},
        "browser": {"timezone": "America/Chicago", "locale": "en-US", "viewport": {"width": 1366, "height": 768}},
        "behavior": {
            "wpm_range": (85, 115), "typo_rate": 0.07, "typo_correction_delay": (100, 300),
            "scroll_chunk": (100, 280), "scroll_sessions": (5, 9), "back_scroll_chance": 0.18,
            "read_pause_range": (12, 25), "idle_drift_chance": 0.40, "pre_click_hover_ms": (200, 550),
            "result_position_weights": [4, 4, 3, 3, 3, 2, 2, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "linda_chicago",
        "mlx_profile_id": _pid(3),
        "email": "linda.bakes.chi@gmail.com",
        "persona": {"name": "Linda", "age": 58, "city": "Chicago"},
        "browser": {"timezone": "America/Chicago", "locale": "en-US", "viewport": {"width": 1280, "height": 800}},
        "behavior": {
            "wpm_range": (20, 35), "typo_rate": 0.05, "typo_correction_delay": (800, 1500),
            "scroll_chunk": (80, 200), "scroll_sessions": (4, 7), "back_scroll_chance": 0.22,
            "read_pause_range": (18, 40), "idle_drift_chance": 0.50, "pre_click_hover_ms": (400, 900),
            "result_position_weights": [6, 5, 4, 3, 2, 1, 1, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "james_london",
        "mlx_profile_id": _pid(4),
        "email": "james.finance.uk@gmail.com",
        "persona": {"name": "James", "age": 41, "city": "London"},
        "browser": {"timezone": "Europe/London", "locale": "en-GB", "viewport": {"width": 1920, "height": 1080}},
        "behavior": {
            "wpm_range": (60, 80), "typo_rate": 0.03, "typo_correction_delay": (200, 500),
            "scroll_chunk": (150, 350), "scroll_sessions": (3, 6), "back_scroll_chance": 0.10,
            "read_pause_range": (8, 18), "idle_drift_chance": 0.30, "pre_click_hover_ms": (120, 300),
            "result_position_weights": [6, 5, 4, 3, 2, 2, 1, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "priya_la",
        "mlx_profile_id": _pid(5),
        "email": "priya.design.la@gmail.com",
        "persona": {"name": "Priya", "age": 29, "city": "Los Angeles"},
        "browser": {"timezone": "America/Los_Angeles", "locale": "en-US", "viewport": {"width": 1536, "height": 864}},
        "behavior": {
            "wpm_range": (65, 90), "typo_rate": 0.04, "typo_correction_delay": (180, 450),
            "scroll_chunk": (180, 420), "scroll_sessions": (2, 5), "back_scroll_chance": 0.07,
            "read_pause_range": (5, 12), "idle_drift_chance": 0.35, "pre_click_hover_ms": (100, 280),
            "result_position_weights": [5, 5, 4, 3, 3, 2, 1, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "tom_houston",
        "mlx_profile_id": _pid(6),
        "email": "tom.diy.houston@gmail.com",
        "persona": {"name": "Tom", "age": 47, "city": "Houston"},
        "browser": {"timezone": "America/Chicago", "locale": "en-US", "viewport": {"width": 1280, "height": 720}},
        "behavior": {
            "wpm_range": (18, 30), "typo_rate": 0.12, "typo_correction_delay": (600, 1500),
            "scroll_chunk": (120, 300), "scroll_sessions": (3, 6), "back_scroll_chance": 0.15,
            "read_pause_range": (10, 22), "idle_drift_chance": 0.45, "pre_click_hover_ms": (300, 700),
            "result_position_weights": [5, 4, 4, 3, 3, 2, 2, 1],
        },
        "topics": get_random_topics(),
        "is_active": True
    },
    {
        "id": "yuki_seattle",
        "mlx_profile_id": _pid(7),
        "email": "yuki.dev.pnw@gmail.com",
        "persona": {"name": "Yuki", "age": 26, "city": "Seattle"},
        "browser": {"timezone": "America/Los_Angeles", "locale": "en-US", "viewport": {"width": 1440, "height": 900}},
        "behavior": {
            "wpm_range": (90, 120), "typo_rate": 0.02, "typo_correction_delay": (100, 250),
            "scroll_chunk": (250, 500), "scroll_sessions": (6, 11), "back_scroll_chance": 0.20,
            "read_pause_range": (15, 35), "idle_drift_chance": 0.35, "pre_click_hover_ms": (100, 300),
            "result_position_weights": [4, 4, 4, 3, 3, 2, 2, 2],
        },
        "topics": get_random_topics(),
        "is_active": True
    }
]

def run_seed():
    print(f"🚀 Uploading {len(PROFILES_TO_UPLOAD)} profiles to Supabase...")
    for profile in PROFILES_TO_UPLOAD:
        try:
            # Upsert will insert or update if 'id' already exists
            supabase.table("bot_profiles").upsert(profile).execute()
            print(f"  ✅ Uploaded: {profile['id']}")
        except Exception as e:
            print(f"  ❌ Failed {profile['id']}: {e}")
            
    print("\n🏁 Seeding complete! You can verify this in your Supabase Table Editor.")

if __name__ == "__main__":
    run_seed()